-- Türkiye: 81 il (idempotent).
-- cities.slug UNIQUE; varsa plate_code ve name güncellenir.

BEGIN;

INSERT INTO cities (name, slug, plate_code) VALUES
  ('Adana', 'adana', 1),
  ('Adıyaman', 'adiyaman', 2),
  ('Afyonkarahisar', 'afyonkarahisar', 3),
  ('Ağrı', 'agri', 4),
  ('Amasya', 'amasya', 5),
  ('Ankara', 'ankara', 6),
  ('Antalya', 'antalya', 7),
  ('Artvin', 'artvin', 8),
  ('Aydın', 'aydin', 9),
  ('Balıkesir', 'balikesir', 10),
  ('Bilecik', 'bilecik', 11),
  ('Bingöl', 'bingol', 12),
  ('Bitlis', 'bitlis', 13),
  ('Bolu', 'bolu', 14),
  ('Burdur', 'burdur', 15),
  ('Bursa', 'bursa', 16),
  ('Çanakkale', 'canakkale', 17),
  ('Çankırı', 'cankiri', 18),
  ('Çorum', 'corum', 19),
  ('Denizli', 'denizli', 20),
  ('Diyarbakır', 'diyarbakir', 21),
  ('Edirne', 'edirne', 22),
  ('Elazığ', 'elazig', 23),
  ('Erzincan', 'erzincan', 24),
  ('Erzurum', 'erzurum', 25),
  ('Eskişehir', 'eskisehir', 26),
  ('Gaziantep', 'gaziantep', 27),
  ('Giresun', 'giresun', 28),
  ('Gümüşhane', 'gumushane', 29),
  ('Hakkâri', 'hakkari', 30),
  ('Hatay', 'hatay', 31),
  ('Isparta', 'isparta', 32),
  ('Mersin', 'mersin', 33),
  ('İstanbul', 'istanbul', 34),
  ('İzmir', 'izmir', 35),
  ('Kars', 'kars', 36),
  ('Kastamonu', 'kastamonu', 37),
  ('Kayseri', 'kayseri', 38),
  ('Kırklareli', 'kirklareli', 39),
  ('Kırşehir', 'kirsehir', 40),
  ('Kocaeli', 'kocaeli', 41),
  ('Konya', 'konya', 42),
  ('Kütahya', 'kutahya', 43),
  ('Malatya', 'malatya', 44),
  ('Manisa', 'manisa', 45),
  ('Kahramanmaraş', 'kahramanmaras', 46),
  ('Mardin', 'mardin', 47),
  ('Muğla', 'mugla', 48),
  ('Muş', 'mus', 49),
  ('Nevşehir', 'nevsehir', 50),
  ('Niğde', 'nigde', 51),
  ('Ordu', 'ordu', 52),
  ('Rize', 'rize', 53),
  ('Sakarya', 'sakarya', 54),
  ('Samsun', 'samsun', 55),
  ('Siirt', 'siirt', 56),
  ('Sinop', 'sinop', 57),
  ('Sivas', 'sivas', 58),
  ('Tekirdağ', 'tekirdag', 59),
  ('Tokat', 'tokat', 60),
  ('Trabzon', 'trabzon', 61),
  ('Tunceli', 'tunceli', 62),
  ('Şanlıurfa', 'sanliurfa', 63),
  ('Uşak', 'usak', 64),
  ('Van', 'van', 65),
  ('Yozgat', 'yozgat', 66),
  ('Zonguldak', 'zonguldak', 67),
  ('Aksaray', 'aksaray', 68),
  ('Bayburt', 'bayburt', 69),
  ('Karaman', 'karaman', 70),
  ('Kırıkkale', 'kirikkale', 71),
  ('Batman', 'batman', 72),
  ('Şırnak', 'sirnak', 73),
  ('Bartın', 'bartin', 74),
  ('Ardahan', 'ardahan', 75),
  ('Iğdır', 'igdir', 76),
  ('Yalova', 'yalova', 77),
  ('Karabük', 'karabuk', 78),
  ('Kilis', 'kilis', 79),
  ('Osmaniye', 'osmaniye', 80),
  ('Düzce', 'duzce', 81)
ON CONFLICT (slug) DO UPDATE
  SET name = EXCLUDED.name,
      plate_code = EXCLUDED.plate_code;

COMMIT;

